apiVersion: config.apps.tanzu.vmware.com/v1alpha4
kind: ConfigurationSlice
metadata:
  name: cook-app-two-config
  namespace: jeremy
spec:
  interval: 30s
  configurationSource: cook-config-source
  content:
  - cook