apiVersion: config.apps.tanzu.vmware.com/v1alpha4
kind: ConfigurationSource
metadata:
  name: cook-app-two-config-source
  namespace: jeremy
spec:
  backends:
    - type: git
      uri: https://github.com/x95castle1/cook-config
      searchPaths: 
      - configs/cook-app-two
      - configs/shared/prod