apiVersion: config.apps.tanzu.vmware.com/v1alpha4
kind: ConfigurationSlice
metadata:
  name: cook-app-two-config
  namespace: jeremy
spec:
  interval: 30s
  configurationSource: cook-app-two-config-source
  content:
    - application/ocho
    - application/save-the-world
    - application
    - application/azure
    - application/logging
    - application/monitoring
    - application/rabbit-mq